export { default as IMG01} from '../../../../assets/images/doctor-01.jpg';
export { default as IMG02} from '../../../../assets/images/doctor-02.jpg';
export { default as IMG03} from '../../../../assets/images/doctor-03.jpg';
export { default as IMG04} from '../../../../assets/images/doctor-04.jpg';
export { default as IMG05} from '../../../../assets/images/doctor-05.jpg';
export { default as IMG06} from '../../../../assets/images/doctor-06.jpg';
export { default as IMG07} from '../../../../assets/images/doctor-07.jpg';
export { default as IMG08} from '../../../../assets/images/doctor-08.jpg';
export { default as IMG09} from '../../../../assets/images/doctor-09.jpg';